AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudfront_validation

  Sample SAM Template for cloudfront_validation

Globals:
  Function:
    Timeout: 3

Resources:
  CloudFrontValidation:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cloudfront_validation/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: makefile

Outputs:
  CloudFrontValidation:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt CloudFrontValidation.Arn
  CloudFrontValidationIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt CloudFrontValidationRole.Arn
